// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxhbaugg6ySaHqaVLf1JFnCrVwd_1upUU',
    appId: '1:626952746415:web:361aa4a2e8d54e7408ab5a',
    messagingSenderId: '626952746415',
    projectId: 'woolthreads-45fc6',
    authDomain: 'woolthreads-45fc6.firebaseapp.com',
    storageBucket: 'woolthreads-45fc6.firebasestorage.app',
    measurementId: 'G-KVNRRQH9WG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEOqueqsw1i13OEbAXznuZQbq45-9OA1w',
    appId: '1:626952746415:android:3c80c264ea2886c508ab5a',
    messagingSenderId: '626952746415',
    projectId: 'woolthreads-45fc6',
    storageBucket: 'woolthreads-45fc6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG0iyNzyJDJV6CtQrB5Qk2Ir14d5NjS9c',
    appId: '1:626952746415:ios:5b4a3b203c098d9308ab5a',
    messagingSenderId: '626952746415',
    projectId: 'woolthreads-45fc6',
    storageBucket: 'woolthreads-45fc6.firebasestorage.app',
    iosBundleId: 'com.example.woolThreads',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG0iyNzyJDJV6CtQrB5Qk2Ir14d5NjS9c',
    appId: '1:626952746415:ios:6f068e33388a6cb608ab5a',
    messagingSenderId: '626952746415',
    projectId: 'woolthreads-45fc6',
    storageBucket: 'woolthreads-45fc6.firebasestorage.app',
    iosBundleId: 'com.example.warmThreads',
  );
}
